#!/usr/bin/env node
require('dotenv/config');

if (!process.env.TOKEN) {
    console.log('token not found, try seeing if it may be in the .env or if it\'s not loaded properly');
}

require('./dist/client.js');
